### ISSUE TITLE
Error report for exile-diary 1.0.0-alpha.11

### ISSUE THREAD

**Issue by Altersandr** [Qt-dev/exile-diary#104]
Error:
```
Error: SQLITE_ERROR: no such table: items
```
OS: Windows NT 10.0.19044

**Comment by Qt-dev** [comment]
Would you have more info about what you were doing when this happened?

**Comment by Altersandr** [comment]
In really sorry, I didn't notice it was the alpha version that I was
installing. But to answer your question, I simply launched your app and
entered the map, as soon as I didn't that the error occurred. I could
reproduce it with ease

**Comment by Qt-dev** [comment]
All good, that's what the alpha is here for :) 
I'll check it out next week, that looks easy enough to reproduce

**Comment by Altersandr** [comment]
I will try again later, when I was setting up the app the first time, the
save button would not work(and then I gave up once I realized it was the
alpha version) , could be that I have missed some of the select options. I
will give my feedback once I mess around some more with the app later today

**Comment by Qt-dev** [comment]
All good,

The 0.3.22 should be stable if you just wanna use it, and if you wanna check and send feedback on the alpha, no rush. I’m working on the stats page right now so I won’t get into much bug fixing for a week I think :)

**Comment by Qt-dev** [comment]
This error should be fixed in the latest alpha (13), in case you want to try things out there again :) 
I'll close this one for now, feel free to reopen it if I got it wrong.

**Comment by Altersandr** [comment]
Hey, i have tried the latest alpha and as it stands out the error i was
getting before is not present now.
