### ISSUE TITLE
On Startup, incubator's error appears - Alpha 11

### ISSUE THREAD

**Issue by mSoul01** [Qt-dev/exile-diary#107]
Log also shows some other missing tables, but only this one gives a Java error on startup.

This was a clean install after Oath completed. Stopped and restarted EDR.

[new.txt](https://github.com/Qt-dev/exile-diary/files/11520236/new.txt)

OS: Windows NT 10.0.22621

**Comment by Qt-dev** [comment]
This looks related to #104 and #105. Something seems to not be set up right on clean install

**Comment by Qt-dev** [comment]
This was related to that DB setup on first start. I cleaned that up on Alpha 13, and it should not happen again.
I'll close this one out for cleanup, feel free to reopen if it is still happening for you.
