### ISSUE TITLE
Error in Run Parsing on some clean installs (1.0.0-alpha.13)

### ISSUE THREAD

**Issue by mSoul01** [Qt-dev/exile-diary#117]
Completed a map run, went to two other locations to get it captured. When click on the map run in the Main tab, get an error 'Error in Run parsing'.
[new.txt](https://github.com/Qt-dev/exile-diary/files/11602615/new.txt)
![Error in Run parsing A](https://github.com/Qt-dev/exile-diary/assets/131409398/06606d1b-4eec-4aae-ad0a-80eb2d382c4d)
![Error in Run parsing B](https://github.com/Qt-dev/exile-diary/assets/131409398/52a5d74d-c8dd-43f0-b1db-005c2e6e707d)

**Comment by mSoul01** [comment]
New clean install, as always.

**Comment by Qt-dev** [comment]
Would you be able to share your Geras.db file ? It should have nothing sensitive in there (Only your chats, however sensitive you make them ;) )
