### ISSUE TITLE
Error report for exile-diary 1.0.0-beta.1

### ISSUE THREAD

**Issue by shakesx** [Qt-dev/exile-diary#124]
![error](https://github.com/Qt-dev/exile-diary/assets/34324732/6829e8ab-6d56-43be-84d0-3fd984d87102)
Error:
```
TypeError: Object has been destroyed
    at Timeout._onTimeout (C:\Users\MJ\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\index.js:455:29)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```
OS: Windows NT 10.0.19044

Error occured after I authenticated my account using OAuth

**Comment by Qt-dev** [comment]
Thank you, I think I see where this error could be, I'll make a fix soon

**Comment by shakesx** [comment]
Now I am receiving the following error when attempting to launch the old version (installed to a separate directory)

![image](https://github.com/Qt-dev/exile-diary/assets/34324732/74625a34-0544-4245-98b8-7e005e71dad0)

**Comment by Qt-dev** [comment]
That was the previous alpha, right?

**Comment by shakesx** [comment]
No, it was exile-diary-setup-0.3.22. Reinstalling it does not fix the error.

**Comment by Qt-dev** [comment]
I think it is an issue with the way I built the overlay window. I think restarting the machine should fix the error too (since it kills the window).
I am going to bed right now but I'll look into it tomorrow morning, I think I have an idea of what's happening.

Sorry for that :)

**Comment by shakesx** [comment]
> I think it is an issue with the way I built the overlay window. I think restarting the machine should fix the error too (since it kills the window). I am going to bed right now but I'll look into it tomorrow morning, I think I have an idea of what's happening.
> 
> Sorry for that :)

All good. Per my edit above, uninstalling Exile Diary Reborn fixes the error.

**Comment by Qt-dev** [comment]
Found the issue. The app was not closing down properly when closing the main window.
This should be fixed and never happen again with beta 2 :)
