### ISSUE TITLE
Disable Overlay Completely Option

### ISSUE THREAD

**Issue by shakesx** [Qt-dev/exile-diary#156]
I would like to request for an option to be implemented that completely disables the overlay window. 

![image](https://github.com/Qt-dev/exile-diary/assets/34324732/dd2469e7-2ba9-4f16-a33a-86efe6f45e17)

I see there is a current option that says 'Enable Overlay Popup Messages', but disabling it only stops new messages from appearing in the overlay window, it doesn't actually disable/remove it.

![image](https://github.com/Qt-dev/exile-diary/assets/34324732/99e4633d-8061-410f-bd02-44bcb14b46f6)

The reason I request this is the overlay window does not play nice with other applications I use (Awakened PoE Trade, Poe Trades Companion). I've actually reverted to using the old Exile Diary because of it.

Let me know if you have any questions. Thank you.

**Comment by Qt-dev** [comment]
Hey there. Sorry to hear that, this option must be bugged. 

May I know which version you are using? I made some changes in 1.0.2 that may fix that issue.

I will look into it tomorrow and will fix that up for a 1.0.4 if 1.0.2 did not fix it :)

**Comment by shakesx** [comment]
> May I know which version you are using? I made some changes in 1.0.2 that may fix that issue.

I am using 1.0.2 currently, still having the issue.

**Comment by Qt-dev** [comment]
I think I fixed it in 1.0.5 or 1.0.4. Is it still not removing the overlay? 
Sorry, forgot to bump this when I fixed it -_-

**Comment by shakesx** [comment]
The issue is fixed.
