### ISSUE TITLE
Profit Breakdown doesn't add up

### ISSUE THREAD

**Issue by zocke1r** [Qt-dev/exile-diary#162]
Apparently the Profit Breakdown and the total don't add up. According to the screenshot i made 73,45c profit on the map, but if i add up all items i only get 27.79c
![image](https://github.com/Qt-dev/exile-diary/assets/12860183/f62cfe6e-1697-4bd2-a3b1-5c30e86b944b)

I think part of the issue is that the Necromancer Silks gets valued at 0 even though it dropped as a 6L so should at least count as a stack of fusings

**Comment by Qt-dev** [comment]
Ha yeah, that sounds like it could be it, even though 6 fusing does not cover the whole difference.
I need to look at pricing in general, there's a lot of weirdness in it, so the fix is probably not going to come very soon, but I will take a look, maybe there's something quick I can do about this.

**Comment by Qt-dev** [comment]
Pricing was all reworked in 1.4.0, this should not happen again
