### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Llonx** [Qt-dev/exile-diary#168]
It does not work , it does not capture me , nothing , besides the pop - up tells me
Tracking Unknown

![menu](https://github.com/Qt-dev/exile-diary/assets/143777409/0d10a547-03c0-4119-b6ac-397f8b8d4bff)

![ingame](https://github.com/Qt-dev/exile-diary/assets/143777409/afd015aa-203e-4bae-bee1-1c1ead7e81b7)

**Comment by Llonx** [comment]
and he is logged in and recognizes the character...
![loged](https://github.com/Qt-dev/exile-diary/assets/143777409/b36f4cd5-2e10-4d08-a592-5f9c158ef300)

**Comment by Qt-dev** [comment]
Do you have Local Chat enabled in game? If local chat is not enabled, Exile Diary only knows that you entered "something", but cannot read what that thing is. That looks like that could be the issue here.

As a side note, for the screenshots, you need to remove the `screenshot-0000.png` at the end.
It needs to be the folder, not a file in that folder, or it will not be able to read it :)

**Comment by Llonx** [comment]
Yes, I have all the chats activated



![2023-09-01 (3)](https://github.com/Qt-dev/exile-diary/assets/143777409/772ca85f-d4c3-4247-989a-2fe1b48e09d6)

**Comment by Qt-dev** [comment]
Ha, I do not think it reads other languages than English in the logs.

**Comment by Llonx** [comment]
I put the game in English


but...
![error](https://github.com/Qt-dev/exile-diary/assets/143777409/91c42e30-ce03-4480-8982-eb8886d7e4be)





After closing and opening the program many times and the character not recognizing me, it seemed to work



![work](https://github.com/Qt-dev/exile-diary/assets/143777409/e7b03375-f89d-4dce-bf22-43a525eda32c)




then I tried to put another random map to see if it worked well



![map](https://github.com/Qt-dev/exile-diary/assets/143777409/4b48419f-4899-4bbf-9cd3-9a92f98cf543)



but I got that message again




![fail](https://github.com/Qt-dev/exile-diary/assets/143777409/4c515e54-5f55-4f9b-8eef-1c87b1f2b224)



I finished the map but nothing happened




![2023-09-02 (4)](https://github.com/Qt-dev/exile-diary/assets/143777409/ddcc385d-cfd5-4316-880e-3a0fab3c2e2e)





no report of the latest map




![REP](https://github.com/Qt-dev/exile-diary/assets/143777409/bf78c08c-d6f3-4519-8f5f-2a8fb2d0dd1d)

**Comment by Qt-dev** [comment]
Ha, that "Object is destroyed" is something else. Sorry about that, I am working on it.
To get rid of the error, you need to kill every Exile Diary Reborn process in the CTRL+ALT+DEL menu.

You said you finished the run, how did you finish it?
I rewrote a small guide with more info (https://github.com/Qt-dev/exile-diary/wiki/How-to-track-your-map-runs#tracking-runs), but my question is: Did you finish the run by getting into another map, or by whispering yourself "end" ?

**Comment by Llonx** [comment]
If every time I closed the program I did it from the task manager, and the maps ended by killing the boss

**Comment by Llonx** [comment]
about the word "end" in the first map, which if it's the one I tracked, I don't remember because it took me by surprise, because I didn't think it would work, and the second map didn't tell me anything

**Comment by Qt-dev** [comment]
Exile Diary cannot detect when you kill the boss. To "complete" the map, you need to :
- Enter a new Run area (a map, Delve Mines, or some story map)
 OR
- Send yourself a private message saying `end` (The command would look like: @myCoolCharacterName end).

For the task Manager part, I'm sorry, I'm working on the bug fix but that is the only way today :)

**Comment by Llonx** [comment]
But the first map I did not put "end" or any command and I track them, so let's see if I understood it correctly, every time I finish a map, I put


@myCoolCharacterName end



in local chat?

**Comment by Qt-dev** [comment]
Yes, either that or you start a new map. 
Whenever you enter a new map, Exile Diary will check if it is still tracking a map. And if it is, it will "complete" it automatically. 
The first one counted without you doing anything because you joined another map, so it did exactly that

**Comment by Llonx** [comment]
ok if it worked now, I tried the story map, started a new one, and I put "end" when entering the city and it did track it and on the endgame maps too


The fault was the language and not putting end every time you finish


(if you want to add it to the instructions for use)

**Comment by Qt-dev** [comment]
I added it, yes. I'm glad it's working for you then !
