### ISSUE TITLE
Wrong pricing for 6 socket items

### ISSUE THREAD

**Issue by Didrikos** [Qt-dev/exile-diary#183]
So those 6 socket items are valued at 4 and 5c while they're like 0.5c after selling to vendor. Tracking non-unique items is also disabled so if it counts them then it should be by recipe value.

[diary log](https://imgur.com/a/Wt6t4Sw)

**Comment by Qt-dev** [comment]
Hey there, thanks for reporting.
I think it gets counted properly but shows weirdly in the breakdown of the map. I will take a look

**Comment by Qt-dev** [comment]
I have a fix in for 1.3.0, this should be gone then

**Comment by Qt-dev** [comment]
This should be gone with 1.4 now :)
