### ISSUE TITLE
Object has been destroyed - Error report for exile-diary 1.0.5

### ISSUE THREAD

**Issue by Noctis-** [Qt-dev/exile-diary#188]
Error:
```
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (C:\Users\***\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\index.js:434:25)
    at EventEmitter.emit (node:events:513:28)
    at Tail.<anonymous> (C:\Users\\***\\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ClientTxtWatcher.js:126:37)
    at Tail.emit (node:events:513:28)
    at C:\Users\\***\\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:56:20
    at Array.forEach (<anonymous>)
    at C:\Users\\***\\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:54:43
    at FSReqCallback.wrapper [as oncomplete] (node:fs:675:5)
```
OS: Windows NT 10.0.19045
App: exile-diary 1.0.5

**Comment by Qt-dev** [comment]
Did this happen again in 1.1.0?

**Comment by Noctis-** [comment]
not sure. this is 1.0.5. i thought auto update works, but i checked after
the bug opened, and saw 1.1 is out. i'll test it and update.
sorry if it's a ghost

**Comment by Qt-dev** [comment]
All good. I think there's something triggering that on auto update so you might need to clear the process if it happens, but a full restart should make it ... never happen again, hopefully. 
Or, if it does, it should give you a message that you can click to restart the app cleanly

**Comment by Noctis-** [comment]
Awesome, thanks!

**Comment by rikai** [comment]
This is indeed still happening in 1.1. Specifically, at least in my case, it seems to happen directly after connecting my account which appears to break the ability to request the stash and/or read the client.txt file.

Unsure if that's at all helpful information, but happy to provide more if needed!

**Comment by Noctis-** [comment]
I've been running some maps on 1.1, no issues ... it did happen from memory
when i've went into the trial of the ancestors ... i can try going in again
later today and see if it happens

**Comment by Qt-dev** [comment]
I'll keep this one open to track all the remaining Object is Destroyed errors that still happen. I should have caught most of them with 1.1.1, and the last remaining one should be on autoupdate from before 1.1.1. But I included a fix for that 1.1.1 so it should stop happening with every update FROM 1.1.1.

If anybody gets another, let me know!

**Comment by Noctis-** [comment]
Awesome, thanks for the update!

**Comment by Qt-dev** [comment]
I believe these are all gone now. I'll set it for "in review" and close it after week 1 of the new league or something :)
