### ISSUE TITLE
Modern Item Filters

### ISSUE THREAD

**Issue by shakesx** [Qt-dev/exile-diary#19]
Would it be possible to update the item filter parser to support the following item types:

-Eldritch Implicits (HasSearingExarchImplicit/HasEaterOfWorldsImplicit)
-Item Base Defence Percentile (BaseDefencePercentile)
-Ravaged Blight Maps (UberBlightedMap/Scourged)

I'm not sure if there are other item types, but these are the ones I found in the log file as errors when I attempted to upload a modern item filter (Filterblade Softcore Very Strict).

**Comment by Qt-dev** [comment]
I will take a look at that this week-end

**Comment by Qt-dev** [comment]
Added the last fix in v0.3.15 :)
