### ISSUE TITLE
"6 - link items" still show divine value in search tab

### ISSUE THREAD

**Issue by Kirihan** [Qt-dev/exile-diary#21]
Steps to reproduce:
- get some 6L
- finish the map (whisper end to yourself)
- go to search, any timeframe including that map.
- look at summary, still shows as divine value.

screenshot: 
![image](https://user-images.githubusercontent.com/45792238/192689811-e92ada3e-ed04-45d3-b76e-e50974b5443c.png)

**Comment by Qt-dev** [comment]
This should be fixed with the latest update. I'm running some tests but let me know if it did not fix it for you

**Comment by Kirihan** [comment]
Yeah its good now, thanks!

**Comment by Kirihan** [comment]
The divine price was being used in this file too, edited it

**Comment by Qt-dev** [comment]
Pulled the changes in #23. Thank you for that !

**Comment by Qt-dev** [comment]
Added the last fix in v0.3.15. Let me know if I missed something. I'll close this issue next week if it's all good :)

**Comment by Kirihan** [comment]
thanks, ill test and let you know in a couple days

**Comment by Kirihan** [comment]
this is fixed 👍
