### ISSUE TITLE
Missing Data in Stats

### ISSUE THREAD

**Issue by shakesx** [Qt-dev/exile-diary#225]
This is the same issue as I posted on discord - Here is the db for my character Shakesxt 
[Shakesxt.zip](https://github.com/Qt-dev/exile-diary/files/13202057/Shakesxt.zip)

**Comment by Qt-dev** [comment]
Note for future me :
This is a DB issue with the `league` table.
When you log into another league, it adds to the table from main index's. Then the league view is using these dates to try and spot when each league finishes (newer entry in the `league` table = the league is over).
A few queries use this data, and so they fail at actually getting everything properly.

**Comment by Qt-dev** [comment]
There's a fix in 1.4 for that. Let me know if you ever hit that problem again
