### ISSUE TITLE
hours seem to be undefined in  Title (Most recent x runs)

### ISSUE THREAD

**Issue by YaronFainstein-Vald** [Qt-dev/exile-diary#226]
Attaching screenshot, this is on 1.3.1

![image](https://github.com/Qt-dev/exile-diary/assets/141883170/6a807419-468c-4bbe-9989-08894a656b9a)

**Comment by Qt-dev** [comment]
Oh right I saw that on another screenshot too. Thanks for the report, I'll take a look and fix that soon!

**Comment by Qt-dev** [comment]
This is fixed in v1.4.0. Feel free to reopen the issue if it happens again for you
