### ISSUE TITLE
Map Information from Screenshots not recording

### ISSUE THREAD

**Issue by shakesx** [Qt-dev/exile-diary#232]
Currently in version 1.3.1 map information (IIQ/IIR/Pack Size) is not being recorded from screenshots for me on the map Cemetery (and possibly other maps - another use reported the same issue on Alleyways). Per our discussion, it seems the issue may have started with the release of 1.3.0.

I have attached the dev captures from Cemetery and Alleyways.

[CemeteryDevCaptures.zip](https://github.com/Qt-dev/exile-diary/files/13327613/CemeteryDevCaptures.zip)
[AlleywaysDevCaptures.zip](https://github.com/Qt-dev/exile-diary/files/13327614/AlleywaysDevCaptures.zip)

**Comment by Qt-dev** [comment]
This should be gone with 1.3.2. I'll close it for now but feel free to reopen if it happens again :)
