### ISSUE TITLE
"undefined" is not valid JSON - Error report for exile-diary 1.4.5

### ISSUE THREAD

**Issue by rawrstylin** [Qt-dev/exile-diary#251]
Error:
```
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Inflate.cb (C:\Program Files\Exile Diary Reborn\resources\app.asar\build\main\StashTabsManager.js:27:38)
    at Inflate.zlibBufferOnError (node:zlib:146:8)
    at Inflate.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
OS: Windows NT 10.0.19045
App: exile-diary 1.4.5

**Comment by rawrstylin** [comment]
Hi there - just installed on Windows 10 and I keep getting this error trying to launch the program. I am unable to get to the 1st setup instruction listed in documentation.

**Comment by Qt-dev** [comment]
The configuration part of the documentation is out of date anyway for now.
I changed the login flow a while ago and did not get to update it.

For this error, that's interesting. When you launch the app, does it tell you to login at least or does not launch at all?

**Comment by rawrstylin** [comment]
Hi QT, an update, the application seems to launch now, I see an overlay when launching POE but the program doesn't seem interactable and the overlay doesn't seem to update on zone changes. The program appears in the taskbar but doesn't actually open for me to go into settings and other options.

**Comment by rawrstylin** [comment]
![image](https://github.com/Qt-dev/exile-diary/assets/153256038/34562ba9-083b-456b-b8de-862d1e873343)

**Comment by Qt-dev** [comment]
Interesting. Restarting it does not change anything for you I suppose ?

**Comment by Qt-dev** [comment]
I understand yup, I was in the same situation and that's how I ended up taking over (to get rid of the wonkiness hehe)
I am having breakfast right now but I will have a look to try and see if I can trigger the same bug in here.
Hopefully I get a fix before league start :)

**Comment by rawrstylin** [comment]
This is what appears in-game:

![image](https://github.com/Qt-dev/exile-diary/assets/153256038/a9ded0fe-70d8-4756-9ec7-01bfea7dd3be)

**Comment by Qt-dev** [comment]
Yup, could you give me the logs from %AppData%\exile-diary ?
They should tell me what I need to know to understand what is happening.

The overlay looks like it started and is showing what it should, that's good news at least

**Comment by rawrstylin** [comment]
I think I got it working! I think old exile diary files were conflicting or not properly removed in the uninstall process. I ended up deleting everything in app data roaming and local update folders. Reinstalled the latest version and I got a POE login screen but cant test further since servers are now down. Fingers crossed :)

**Comment by Qt-dev** [comment]
Perfect. Can you try doing Windows+Right arrow when you have the app selected ? 
It looks like it is somehow starting right after your screen and the Windows key + Right or Left arrow should make it pop on your screen

**Comment by rawrstylin** [comment]
Interesting - I have never used that shortcut and it doesn't seem to work on my PC. Really weird... I'll test again once servers are up, I started getting a timeout error so closed application for now.

**Comment by rawrstylin** [comment]
Wow just discovered that the Windows key doesn't work on this keyboard... so much for hand-me-downs from my brother... argh.

**Comment by Qt-dev** [comment]
Haha yeah, that happens. Ok, a couple more solutions then :
- This is a guide of the multiple ways of moving the window back to the screen: https://www.lifewire.com/how-to-move-a-window-that-is-off-screen-4772840
- Try to move the file I just attached (settings.json) into `%AppData%\exile-diary` and restart the app :) 
[settings.json](https://github.com/Qt-dev/exile-diary/files/13619652/settings.json)

**Comment by rawrstylin** [comment]
![image](https://github.com/Qt-dev/exile-diary/assets/153256038/a19abb84-7116-4960-8cc2-49f233b2dd8e)

So far so good :) Haven't tried the settings file yet.
