### ISSUE TITLE
1.4.7 Opening settings gives an "Unexpected Application Error!". (Cannot find module './UltimatumStash.png')

### ISSUE THREAD

**Issue by fask0** [Qt-dev/exile-diary#255]
![image](https://github.com/Qt-dev/exile-diary/assets/45174264/cf5e8334-3607-4fb7-bf29-5d9cda8423f2)

**Comment by Diabolos** [comment]
I got this too, 
Note: it was not doing this until i cleared the client log file so it would stop showing old map runs in "Main" tab

**Comment by Qt-dev** [comment]
Found the error, deploying a fix now. 1.4.8 incoming :)

**Comment by Qt-dev** [comment]
1.4.8 is up and fixes that
