### ISSUE TITLE
SQLITE_ERROR: no such table: items - Error report for exile-diary 1.4.7

### ISSUE THREAD

**Issue by Diabolos** [Qt-dev/exile-diary#256]
When zoning into my hideout from Lioneye's Watch:

Error:
```
Error: SQLITE_ERROR: no such table: items
```
OS: Windows NT 10.0.22621
App: exile-diary 1.4.7

**Comment by Qt-dev** [comment]
I believe you can ignore this one and it will go away by itself.
It will create that table at some point but I do not remember when exactly.

Even if it doesnt, you should be able to ignore it altogether for now

**Comment by Diabolos** [comment]
Okay, if you say it'll go away I'll close it.

**Comment by Diabolos** [comment]
Okay, if you say it'll go away I'll close it.

**Comment by Qt-dev** [comment]
You can keep it open, I will fix it so that it does not happen in the future :)

**Comment by Qt-dev** [comment]
Ha, I found the issue. This should be fixed if you just restart the app.
For reference : It did not set up the DB right when you picked your character. It checks and sets it up if needed on start so restarting the app should fix it for you

**Comment by Diabolos** [comment]
That's awesome, thanks for the quick fix
