### ISSUE TITLE
Currency shards have weird ratios

### ISSUE THREAD

**Issue by Didrikos** [Qt-dev/exile-diary#273]
Would also be nice to exclude items from stats under threshhold specified by user.

**Comment by Qt-dev** [comment]
The threshold thing is one of my next tasks yup. Are the weird ratios due to the fact that poe.ninja is having weird prices or is it something else?

**Comment by Didrikos** [comment]
Some shards are not present on poe.ninja so no idea from where it takes the value but it's way

![obraz](https://github.com/Qt-dev/exile-diary/assets/69087773/7e7f92e8-1c64-4b50-8b7f-427ca0b01f2c)
![obraz](https://github.com/Qt-dev/exile-diary/assets/69087773/b2e7dc74-eb05-4410-a1fd-c722fea5651d)

**Comment by Qt-dev** [comment]
I got a fix for shard pricing in my dev version, I'll look at these 2 to see if that fixes it then

**Comment by Qt-dev** [comment]
And the answer to where it comes from : It uses the actual orb and splits the price by the number of splinters to make an orb :)

**Comment by Didrikos** [comment]
Possible but doesn't match the price anyways, 18 horizon shards can't be 5.35c when they're 0.33c as full.

**Comment by Qt-dev** [comment]
Yup yup that's the bug. It's doing some weird calculation in a weird way, and so most shards and some other currencies are priced weirdly. When I deploy the fix I have in Dev, you should be able to hit "Reprice" and it should all be fixed in a few seconds using the proper calculation

**Comment by Qt-dev** [comment]
This should be fixed now, I'll leave it open for league start but probably close it next week
