### ISSUE TITLE
Cannot convert undefined or null to object - Error report for exile-diary 1.4.13

### ISSUE THREAD

**Issue by MeTeC-FR** [Qt-dev/exile-diary#274]
Error:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at InventoryGetter.logKillCount (C:\Users\Tom\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\KillTracker.js:28:12)
    at InventoryGetter.emit (node:events:525:35)
    at InventoryGetter.getCurrentInventory (C:\Users\Tom\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\InventoryGetter.js:90:14)
    at async C:\Users\Tom\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\InventoryGetter.js:32:27
```
OS: Windows NT 10.0.19045
App: exile-diary 1.4.13

**Comment by Didrikos** [comment]
That's just connection issues due to unstable site, app can't get information about your chest,

**Comment by Qt-dev** [comment]
@Didrikos : Really? It should error before that if it is the case, shouldn't it? I am looking into what's happening that would trigger that but I have had a hard time finding a pattern so far

**Comment by Qt-dev** [comment]
Found the issue. It is indeed related to connection issues.
Cloudflare returns some errors that the app deals with, but then my handling of that fails and returns this error. I wonder if I should retry a bit more when that happens, but I have a fix for the 2 kind of errors that trigger with this.
I'll see when I can push them

**Comment by Qt-dev** [comment]
This should not happen again with 1.4.14
