### ISSUE TITLE
Pouch items were not counted.

### ISSUE THREAD

**Issue by samos667** [Qt-dev/exile-diary#276]
I am farming harvest and storing lifeforce in the league bag. I have noticed that the currency I receive and stock in the bag is not tracked.
![image](https://github.com/Qt-dev/exile-diary/assets/50653464/1ca3aab2-cb54-457b-907e-4647d9efb88e)

![image](https://github.com/Qt-dev/exile-diary/assets/50653464/6101231e-bf3a-431f-a2b6-7ce1ecd56869)

**Comment by samos667** [comment]
Maybe relate to this error message https://github.com/Qt-dev/exile-diary/issues/272#issuecomment-1863690231

**Comment by Qt-dev** [comment]
Ha, I do not think it is related. I think it's all because they store it in another "inventory" and the app is not setup to look into that. I'll add a fix in the next version, that should be pretty easy

**Comment by Qt-dev** [comment]
This should be fixed with 1.4.14
