### ISSUE TITLE
Solved - POESESSID once again not working?

### ISSUE THREAD

**Issue by Cefwyn** [Qt-dev/exile-diary#33]
I just found this sweet update to the amazing exile diary - sadly I get the same "POESESSID entered correctly?" error message that I received in the original.

Did the fix break again? Or is it more likely I am doing something wrong?

**Comment by Cefwyn** [comment]
My bad - after going to Users\USERNAME\AppData\Roaming\ and deleting the folder: exile-diary (where it saved my diary data of the last few years, including the settings) and reinstalling - it now works.

**Comment by Qt-dev** [comment]
Sorry you lost everything, but thanks for the good words :)
