### ISSUE TITLE
Javascript error when starting up program

### ISSUE THREAD

**Issue by HeyZeus1232** [Qt-dev/exile-diary#73]
![error](https://user-images.githubusercontent.com/111616953/236190211-d8f8accb-c6ae-44d7-b0e9-346449c7e2c4.png)

this is the error that comes up when i try to start the program.

**Comment by HeyZeus1232** [comment]
v1.0.0-alpha.3

I tired alpha 2 as well, haven't tried alpha 4 yet, I'm guessing it would still be the same issue, unless you've changed something related?

**Comment by HeyZeus1232** [comment]
> Oh yeah found the issue. Some error due to old code and new code trying to play well together, sorry about that. I'll push a bugfix when I make alpha 5

Hey thanks, just curious, was this not happening to anyone else, and just me? Was this reproducible somehow? Just wondering what the issue is on my end then aswell

**Comment by Qt-dev** [comment]
I think it was some weird racing conditions of stuff not being setup in the right order. I could definitely force it, but not sure how it ended up happening only to you (as far as I've seen). Maybe that was because you had not done your settings yet? Not sure tbh...

Try it with Alpha.5 and let me know if that still errors

**Comment by HeyZeus1232** [comment]
Error:
```Error: Cannot find module 'C:\Users\---\AppData\Roaming\exile-diary\settings.json'
Require stack:
- C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\SettingsManager.js
- C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\Responder.js
- C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109751)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at SettingsManager.<anonymous> (C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\SettingsManager.js:92:41)
    at step (C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\SettingsManager.js:56:23)
    at Object.next (C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\SettingsManager.js:37:53)
    at C:\Users\---\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\SettingsManager.js:31:71
```
OS: Windows NT 10.0.19045




this is the new error that comes up. fresh install, other versions all completely removed before installing alpha 5.

**Comment by Qt-dev** [comment]
Hmm.... That file does not exist at all, right?

**Comment by HeyZeus1232** [comment]
Yeah its not anywhere doesn't seem to be getting created

**Comment by Qt-dev** [comment]
Hmm I am going to try and run through that same error in the week. In the meantime, can you try adding an empty file to see if it unblocks the whole thing? I would send you one but github does not seem to like sending json files -_-

All you need to do is to create a settings.json file with notepad or whatever, and add this content to it:
```json
{}
```

**Comment by HeyZeus1232** [comment]
So creating the file allows the program to run, but when i press "settings" tab, it comes with this error:

Unexpected Application Error!
Error invoking remote method 'get-characters': Error: Missing poesessid or accountName
Error: Error invoking remote method 'get-characters': Error: Missing poesessid or accountName
    at a.invoke (node:electron/js2c/renderer_init:2:7610)

**Comment by Qt-dev** [comment]
Dang, that's ... 
Ok, I see this one, and how to fix it, but I will not do it today. 

To unblock it for yourself, you'll need to turn that settings file into :
```json
{
    "accountName": "YOUR_ACCOUNT_NAME",
    "poesessid": "YOUR_POESESSID"
}
```

Replace the two variables with proper value and you should be good
This should fix it for you for now, while I spend a bit more time figuring out why settings.json creation does not work

**Comment by HeyZeus1232** [comment]
it comes up with another error, and i added this line from the settings json from the stable version.

"activeProfile":{"characterName":"CHAR_NAME_HERE","league":"Crucible"}

The program runs, and i can click the settings tab now, but it seems all the other tabs are empty, i cant run the game at the moment so i cant test it, but i can tomorrow after i finish work.

**Comment by Qt-dev** [comment]
Oh yeah, the alpha does not have these pages yet. I'm implementing them as fast as I can :) 
For now it has the main page, the mods recognition from screenshot, and all the stats in each map

**Comment by Qt-dev** [comment]
I found the issue and got the fix ready for the next alpha release, FYI.
I am working on adding Oauth instead of Poesessid. That should be doable this week, and the alpha version I make from that will include the fix

**Comment by Qt-dev** [comment]
alpha 6 should fix all that now. Not only does it include a fix for config stuff, but it also replaces all that poesessid with proper oauth

**Comment by Qt-dev** [comment]
I'll mark this as in review. If I do not hear from you until tomorrow, I'll consider this resolved with the latest alpha then :)

**Comment by HeyZeus1232** [comment]
> 

hey, sorry i have not had any time this past week to do anything, I did a complete clean install of alpha 10 and it booted up, But when i logged into POE account it comes up with this:

![newerror](https://github.com/Qt-dev/exile-diary/assets/111616953/921b8866-e619-4346-b4d1-cd91731d5373)

**Comment by HeyZeus1232** [comment]
> I'll mark this as in review. If I do not hear from you until tomorrow, I'll consider this resolved with the latest alpha then :)

hey, sorry i have not had any time this past week to do anything, I did a complete clean install of alpha 10 and it booted up, But when i logged into POE account it comes up with this:

![newerror](https://github.com/Qt-dev/exile-diary/assets/111616953/31483392-0036-4847-b4b3-73367d312c7f)

**Comment by Qt-dev** [comment]
No worries hehe. I was just trying to clean up what I thought I fixed :) 
There's a couple issues on clean installs, I'll look at that this week. Sorry about that

**Comment by Qt-dev** [comment]
This should be cleaned up now. I'll close it for now, don't hesitate to reopen it and shout at me if that is not the case :)
