### ISSUE TITLE
Error on clean install - Alpha 5

### ISSUE THREAD

**Issue by mSoul01** [Qt-dev/exile-diary#85]
Log file attached.

Error:
```
Error: ENOENT: no such file or directory, stat 'C:\Users\Geras\AppData\Roaming\exile-diary\settings.json'
```
OS: Windows NT 10.0.22621
[new.txt](https://github.com/Qt-dev/exile-diary/files/11423728/new.txt)

**Comment by Qt-dev** [comment]
Hmm thank you for this, I think there's something weird with the settings creation at the begining. It looks like you're hitting the same issue as #73

**Comment by mSoul01** [comment]
Yeah. I can't get it to start unless I install the original version of ED. It's looking in that folder for the settings.json file.

**Comment by Qt-dev** [comment]
Found the issue. I got the fix, I will probably release it aigu the API changes, which may also take care of the errors like that 429 you have been getting

**Comment by Qt-dev** [comment]
This should be all cleared up for now. I'll close this one one for cleanup but feel free to reopen it if I got it wrong :)
