### ISSUE TITLE
Auth error on new install - Alpha 06

### ISSUE THREAD

**Issue by mSoul01** [Qt-dev/exile-diary#98]
A few errors possible in the log. This is based on no previously installed Exile Diary, and clean install of Exile Diary Reborn.
[new.txt](https://github.com/Qt-dev/exile-diary/files/11470107/new.txt)

**Comment by Qt-dev** [comment]
I will need to :
- [ ] Nuke the install from my machine
- [ ] Run install
- [ ] Fix everything

**Comment by mSoul01** [comment]
Alpha 11 works!
