### ISSUE TITLE
Error while getting characters from the GGG API: Missing Active Profile - Alpha 08

### ISSUE THREAD

**Issue by mSoul01** [Qt-dev/exile-diary#99]
oath request to POE website successful, redirects from webpage back to app, then error appears.

Log attached
[new.txt](https://github.com/Qt-dev/exile-diary/files/11470834/new.txt)

**Comment by Qt-dev** [comment]
This should be fixed with the latest Alpha (10), let me know if you still get this error :)

**Comment by Qt-dev** [comment]
Closing this for now. Do not hesitate to reopen a new one if you find that the issue happens again at some point
